name = "TOGRegistry"
uuid = "5e4adcd5-c399-4ce6-9383-58d4246097f5"
repo = "https://github.com/1m1-github/TOGRegistry.git"

[packages]
11295428-077f-4f85-91e7-f02acc9f1bc4 = { name = "TOGPrivacy", path = "T/TOGPrivacy" }
2f8be1b4-0caf-4444-968c-3426b7899264 = { name = "TOGBasicTools", path = "T/TOGBasicTools" }
4252c4d5-dd2c-4ffa-8887-0b0edb8dbe1e = { name = "TOGPowerOfAttorney", path = "T/TOGPowerOfAttorney" }
5152f97e-43a2-45f4-8f25-050dac6567e0 = { name = "TOGAdvice", path = "T/TOGAdvice" }
59e1c01a-66d3-4f31-a2af-c2f41340710f = { name = "LoopOS", path = "L/LoopOS" }
72627af7-d4be-41d5-ae1d-91b43e08b9fe = { name = "TOGLogging", path = "T/TOGLogging" }
7a18482f-397a-43d3-bca4-098266640121 = { name = "TOGAnthropic", path = "T/TOGAnthropic" }
924bc2a5-e083-4d12-bf67-a842e8246f09 = { name = "TOGIntelligenceLocal", path = "T/TOGIntelligenceLocal" }
9d53f387-cc57-4756-9043-cdf1274bde3f = { name = "TOGZMQ", path = "T/TOGZMQ" }
af1d9ce1-dab3-4208-a785-3251d27ca748 = { name = "TOGREPL", path = "T/TOGREPL" }
b2cfa71b-e52f-4128-a186-18ce7f67a068 = { name = "TOGXAI", path = "T/TOGXAI" }
bb1d05a6-2533-48e7-9207-d1905862d9ea = { name = "TOGIntelligenceHuman", path = "T/TOGIntelligenceHuman" }
c9101ee6-f480-4f04-b2e3-e4d672b7c53b = { name = "TOG", path = "T/TOG" }
e2f8f2e7-7db2-4418-a39e-2216e388f2df = { name = "TOGRay", path = "T/TOGRay" }
f1fe39fb-6393-41e1-971c-b02c3e510d65 = { name = "TOGCaching", path = "T/TOGCaching" }
f24ce740-eac4-403b-aa84-6d398323826e = { name = "TOGLearning", path = "T/TOGLearning" }
f4cec632-eb7e-43bd-a4c1-cac080e970db = { name = "TOGColor", path = "T/TOGColor" }
fce80b97-c5fb-4a1c-bec5-c7fe9f180d45 = { name = "TOGInstall", path = "T/TOGInstall" }
