name = "TOGRegistry"
uuid = "56d3e4df-d656-46b9-9daf-2438a54de69c"
repo = "https://github.com/1m1-github/TOGRegistry.git"

[packages]
0a395a96-41e2-4445-9546-93546e069562 = { name = "TOGAnthropic", path = "T/TOGAnthropic" }
1c1d7378-2f6c-44c0-88d7-7a23e88bf3e0 = { name = "TOGAdvice", path = "T/TOGAdvice" }
1df27153-9956-4e1b-b91b-fbaa2595f438 = { name = "TOGPowerOfAttorney", path = "T/TOGPowerOfAttorney" }
417b0ba9-c6e5-4172-8beb-726a968b3beb = { name = "TOGBasicTools", path = "T/TOGBasicTools" }
67d9d36d-43fb-464e-82e3-4f04d09dacc1 = { name = "TOGLearning", path = "T/TOGLearning" }
737b443f-5b68-4fde-ac0f-501ab7f5c9a4 = { name = "TOGInstall", path = "T/TOGInstall" }
894673ee-413c-4601-8a2e-415a0e884e29 = { name = "TOG", path = "T/TOG" }
9a85759a-e2d6-4eb5-ba00-7f48a432d541 = { name = "LoopOS", path = "L/LoopOS" }
afe36212-cf87-4c61-af1f-196f295ed07d = { name = "TOGXAI", path = "T/TOGXAI" }
ca4dc87f-8132-4d7b-94ac-048606885fda = { name = "TOGLogging", path = "T/TOGLogging" }
cef1c0f6-0c08-4e95-906e-2b73d07538e0 = { name = "TOGCaching", path = "T/TOGCaching" }
db865f57-0a4c-442e-9c28-0e380b845d13 = { name = "TOGIntelligenceLocal", path = "T/TOGIntelligenceLocal" }
f4a02697-7cd1-461d-8820-6cd877ce326b = { name = "TOGZMQ", path = "T/TOGZMQ" }
fe9bd503-75ce-4c08-8bd5-2629e4df7c13 = { name = "TOGPrivacy", path = "T/TOGPrivacy" }
