name = "TOGRegistry"
uuid = "5e4adcd5-c399-4ce6-9383-58d4246097f5"
repo = "https://github.com/1m1-github/TOGRegistry.git"

[packages]
11295428-077f-4f85-91e7-f02acc9f1bc4 = { name = "TOGPrivacy", path = "T/TOGPrivacy" }
1b934daf-0caa-4168-a756-278b3bd23fdd = { name = "TOGZMQClient", path = "T/TOGZMQClient" }
2f8be1b4-0caf-4444-968c-3426b7899264 = { name = "TOGBasicTools", path = "T/TOGBasicTools" }
37fee73d-ef03-4fc1-b8ee-b96b35d47696 = { name = "TOGDona", path = "T/TOGDona" }
3a696844-2fa8-43b6-8c1f-b67ef9a861fa = { name = "TOGState", path = "T/TOGState" }
4252c4d5-dd2c-4ffa-8887-0b0edb8dbe1e = { name = "TOGPowerOfAttorney", path = "T/TOGPowerOfAttorney" }
5152f97e-43a2-45f4-8f25-050dac6567e0 = { name = "TOGAdvice", path = "T/TOGAdvice" }
59e1c01a-66d3-4f31-a2af-c2f41340710f = { name = "LoopOS", path = "L/LoopOS" }
72627af7-d4be-41d5-ae1d-91b43e08b9fe = { name = "TOGLogging", path = "T/TOGLogging" }
7a18482f-397a-43d3-bca4-098266640121 = { name = "TOGAnthropic", path = "T/TOGAnthropic" }
8f0b5ac4-1c02-47b5-9257-2ee9debc9305 = { name = "TOGZMQAPIClient", path = "T/TOGZMQAPIClient" }
924bc2a5-e083-4d12-bf67-a842e8246f09 = { name = "TOGIntelligenceLocal", path = "T/TOGIntelligenceLocal" }
9d46ef08-7eb0-4375-be84-f8f6ddc49f8f = { name = "TOGZMQAPIServer", path = "T/TOGZMQAPIServer" }
9d53f387-cc57-4756-9043-cdf1274bde3f = { name = "TOGZMQ", path = "T/TOGZMQ" }
af1d9ce1-dab3-4208-a785-3251d27ca748 = { name = "TOGREPL", path = "T/TOGREPL" }
b2cfa71b-e52f-4128-a186-18ce7f67a068 = { name = "TOGXAI", path = "T/TOGXAI" }
bb1d05a6-2533-48e7-9207-d1905862d9ea = { name = "TOGIntelligenceHuman", path = "T/TOGIntelligenceHuman" }
be2ccf55-320f-4cf9-a7f1-33931dc8ea12 = { name = "TOGTypst", path = "T/TOGTypst" }
c9101ee6-f480-4f04-b2e3-e4d672b7c53b = { name = "TOG", path = "T/TOG" }
d4c73057-c471-4b8c-b1af-85ad29d2a3b0 = { name = "TOGBroadcastBrowser", path = "T/TOGBroadcastBrowser" }
d82a7266-ecbf-4de4-94ee-583468f75bc2 = { name = "TOGMatrix", path = "T/TOGMatrix" }
e2f8f2e7-7db2-4418-a39e-2216e388f2df = { name = "TOGRay", path = "T/TOGRay" }
e9b587c0-12e9-4cbe-ad2f-11c87a054381 = { name = "TOGIntelligence", path = "T/TOGIntelligence" }
f1fe39fb-6393-41e1-971c-b02c3e510d65 = { name = "TOGCaching", path = "T/TOGCaching" }
f24ce740-eac4-403b-aa84-6d398323826e = { name = "TOGLearning", path = "T/TOGLearning" }
f4cec632-eb7e-43bd-a4c1-cac080e970db = { name = "TOGColor", path = "T/TOGColor" }
fce80b97-c5fb-4a1c-bec5-c7fe9f180d45 = { name = "TOGInstall", path = "T/TOGInstall" }
fdb9b95c-25fa-4492-a90f-35931e1d92fd = { name = "TOGJanet", path = "T/TOGJanet" }
